// Comprehensive curated blocklist of disposable, temporary, and burner email domains
// Covers major disposable providers (TempMail, GuerrillaMail, 10MinuteMail, Mailinator, ThrowawayMail, etc.)

export const DISPOSABLE_EMAIL_DOMAINS: ReadonlySet<string> = new Set([
  // Mailinator & derivatives
  'mailinator.com',
  'mailinater.com',
  'mailinator2.com',
  'suremail.info',
  'spamherelots.com',
  'binkmail.com',
  'safetymail.info',
  'chammy.info',
  'letthemeatspam.com',
  'tradermail.info',
  'notmailinator.com',
  'veryrealemail.com',

  // Guerrilla Mail & derivatives
  'guerrillamail.com',
  'guerrillamail.net',
  'guerrillamail.org',
  'guerrillamail.biz',
  'guerrillamailblock.com',
  'sharklasers.com',
  'grr.la',
  'pokemail.net',
  'spam4.me',

  // 10 Minute Mail & derivatives
  '10minutemail.com',
  '10minutemail.net',
  '10minutemail.org',
  '10minutemail.co.uk',
  '10minutemail.de',
  '10minutesmail.com',
  '10minute-mail.com',
  '10minmail.com',
  '10minutemail.be',

  // TempMail & derivatives
  'tempmail.com',
  'tempmail.net',
  'tempmail.org',
  'temp-mail.org',
  'temp-mail.io',
  'temp-mail.ru',
  'tempmailaddress.com',
  'tempmailo.com',
  'temp-mails.com',
  'tempinbox.com',
  'tempinbox.org',
  'tmpmail.net',
  'tmpmail.org',
  'tmpeml.com',

  // ThrowAwayMail & TrashMail
  'throwawaymail.com',
  'throwaway.email',
  'throwawaymail2.com',
  'trashmail.com',
  'trashmail.net',
  'trashmail.org',
  'trashmail.me',
  'trash-mail.com',
  'trashmail.at',
  'rcpt.at',
  'curryrascal.com',

  // YOPmail & derivatives
  'yopmail.com',
  'yopmail.fr',
  'yopmail.net',
  'cool.fr.nf',
  'jetable.fr.nf',
  'nospam.ze.tc',
  'nomail.xl.cx',
  'mega.zik.dj',
  'speed.1s.fr',
  'courriel.fr.nf',
  'moncourrier.fr.nf',
  'monemail.fr.nf',
  'monmail.fr.nf',

  // Dispostable, FakeInbox, BurnerMail & Others
  'dispostable.com',
  'fakeinbox.com',
  'fakemailgenerator.com',
  'getairmail.com',
  'airmail.news',
  'burnermail.io',
  'burnmail.co',
  'generator.email',
  'mohmal.com',
  'mohmal.in',
  'mohmal.im',
  'getnada.com',
  'abavala.com',
  'inboxbear.com',
  'dropmail.me',
  '10mail.org',
  'emkei.cz',
  'crazymailing.com',
  'mailcatch.com',
  'maildrop.cc',
  'harakirimail.com',
  'mytemp.email',
  'emailondeck.com',
  'minuteinbox.com',
  'zillamail.com',
  'nada.ltd',
  'nada.email',
  'inboxkitten.com',
  'luxusmail.org',
  'burnermail.org',
  'internxt.com/temporary-email',
  'emailfake.com',
  'generator.email',
  'crazymailing.com',
  'armyspy.com',
  'cuvox.de',
  'dayrep.com',
  'fleckens.hu',
  'gustr.com',
  'jourrapide.com',
  'rhyta.com',
  'superrito.com',
  'teleworm.us',
  'tinemail.com',
  'drdrb.net',
  'spambog.com',
  'spambog.de',
  'spambog.ru',
  'spamday.com',
  'spamfree24.org',
  'spamgourmet.com',
  'spamspot.com',
  'tmail.ws',
  'trashymail.com',
  'wegwerfmail.de',
  'wegwerfmail.net',
  'wegwerfmail.org',
  'whyspam.me',
  'zoemail.org',
  'disposablemail.com',
  'mailnesia.com',
  'mailnull.com',
  'mailsac.com',
  'mintemail.com',
  'mt2015.com',
  'nobulk.com',
  'noclickemail.com',
  'nodisposable.com',
  'nofeeemail.com',
  'no-spam.ws',
  'notsharingmy.info',
  'nowmymail.com',
  'nullbox.org',
  'objectmail.com',
  'onewaymail.com',
  'ourproject.org',
  'ovpn.to',
  'pookmail.com',
  'privatdemail.net',
  'quickemail.info',
  'quickinbox.com',
  'rcpt.info',
  'recode.me',
  'recursor.net',
  'redchan.it',
  'regbypass.com',
  'rejectmail.com',
  'repostmail.com',
  'rmq.me',
  'rootprotect.com',
  'safe-mail.net',
  'safemail.in',
  'safetymail.info',
  'safetypost.de',
  'sandmail.org',
  'savemyass.org',
  'saynotospams.com',
  'schafmail.de',
  'schreibe.org',
  'secretmail.net',
  'secure-mail.biz',
  'sendspamhere.com',
  'sharedmailbox.org',
  'shieldedmail.com',
  'shortmail.net',
  'sibmail.com',
  'sinnlos-mail.de',
  'siteposter.net',
  'skeefmail.com',
  'slmail.me',
  'smartemail.co.uk',
  'smashmail.de',
  'smellfear.com',
  'snkmail.com',
  'sofort-mail.de',
  'sogetthis.com',
  'solidmail.info',
  'soodonims.com',
  'spamavert.com',
  'spambob.com',
  'spambob.net',
  'spambob.org',
  'spambox.info',
  'spambox.us',
  'spameater.org',
  'spamex.com',
  'spamhole.com',
  'spaml.com',
  'spaml.de',
  'spammotel.com',
  'spamobox.com',
  'spampal.net',
  'spamtrap.ro',
  'spamtrail.com',
  'speedpost.net',
  'squizzy.de',
  'ssl.tls.cloudns.asia',
  'superstachel.de',
  'suremail.info',
  'tagmail.net',
  'tafmail.com',
  'techgroup.me',
  'teewars.org',
  'tempail.com',
  'tempemail.co',
  'tempemail.net',
  'tempermail.com',
  'tempm.com',
  'tempr.email',
  'throwawayemailaddress.com',
  'ticket-system.org',
  'tittbit.in',
  'tny.im',
  'tradermail.info',
  'trash-mail.at',
  'trash-mail.ch',
  'trash-mail.de',
  'trashmail.at',
  'trashmail.ch',
  'trashmail.de',
  'trashmail.io',
  'trashmail.ws',
  'trashmailbox.com',
  'trashmailer.com',
  'trashymail.com',
  'tvsubtitles.net',
  'uacct.com',
  'uggsrock.com',
  'uk2.net',
  'ultra.fartit.com',
  'unmail.co',
  'unmail.me',
  'unsolicitedmail.org',
  'upwardmail.com',
  'urhen.com',
  'usermail.com',
  'utmostmail.com',
  'vmani.com',
  'vubinter.net',
  'w-m.pl',
  'wastemail.com',
  'webemail.me',
  'webmailserver.org',
  'wellmail.info',
  'wetrainbayarea.com',
  'wetrainbayarea.org',
  'wh4f.org',
  'whyspam.me',
  'willselfdestruct.com',
  'wimsg.com',
  'winemaven.in',
  'wolframalpha.info',
  'wuzup.net',
  'wuzupmail.net',
  'wwwnew.eu',
  'xagloo.com',
  'xent.com',
  'xmaily.com',
  'xoxox.cc',
  'ypmail.webcam',
  'yapped.net',
  'yep.it',
  'yogamaven.com',
  'yomail.info',
  'yopmail.gq',
  'yopmail.pk',
  'yopmail.pp.ua',
  'ypmail.com',
  'ytad.net',
  'ytb.pw',
  'ytbe.pw',
  'yuurok.com',
  'z80.de',
  'zaffre.net',
  'zehnminutenmail.de',
  'zetmail.com',
  'zippymail.info',
  'zoemail.com',
  'zoemail.net',
  'zoemail.org',
  'zomg.info',
  'zootemail.com',
  'zre.me',
  'zxcv.de',
  'zxcvbnm.co.uk',
  'zzpost.net',
]);

const DISPOSABLE_KEYWORD_PATTERNS = [
  /temp.*mail/i,
  /throw.*away/i,
  /dispos.*mail/i,
  /fake.*mail/i,
  /trash.*mail/i,
  /10min.*mail/i,
  /guerrilla.*mail/i,
  /burner.*mail/i,
  /minute.*inbox/i,
];

/**
 * Checks whether an email address uses a known disposable or burner domain.
 */
export function isDisposableDomain(email: string): boolean {
  if (!email || !email.includes('@')) return false;
  const parts = email.split('@');
  if (parts.length !== 2) return false;

  const domain = parts[1].toLowerCase().trim();
  if (DISPOSABLE_EMAIL_DOMAINS.has(domain)) {
    return true;
  }

  // Check subdomains (e.g., sub.mailinator.com)
  const hostParts = domain.split('.');
  for (let i = 1; i < hostParts.length - 1; i++) {
    const parentDomain = hostParts.slice(i).join('.');
    if (DISPOSABLE_EMAIL_DOMAINS.has(parentDomain)) {
      return true;
    }
  }

  // Check common disposable keywords in domain name
  for (const pattern of DISPOSABLE_KEYWORD_PATTERNS) {
    if (pattern.test(domain)) {
      return true;
    }
  }

  return false;
}
